[font]
size = 14.0

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen Console NF"
style = "Bold"

[font.italic]
family = "HackGen Console NF"
style = "Regular"

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[font.offset]
x = 0
y = 1

# vim: set ft=toml ts=2 sw=2 sts=2 et :
