[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "CreateNewTab"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "SelectNextTab"
key = "Tab"
mods = "Command"

[[keyboard.bindings]]
action = "SelectPreviousTab"
key = "Tab"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SelectTab1"
key = "1"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab2"
key = "2"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab3"
key = "3"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab4"
key = "4"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab5"
key = "5"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab6"
key = "6"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab7"
key = "7"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab8"
key = "8"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab9"
key = "9"
mods = "Command"

[[keyboard.bindings]]
chars = "alacritty msg config window.opacity=1.0\u000d"
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "alacritty msg config window.opacity=0.9\u000d"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001by"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bO"
key = "O"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001bZ"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001b1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b,"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b("
key = "Key9"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001b)"
key = "Key0"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001b`"
key = "`"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b;"
key = "Semicolon"
mods = "Alt"

# vim: set ft=toml ts=2 sw=2 sts=2 et :
